### ISSUE TITLE
 some tabs are not restored

### ISSUE THREAD

**Issue by perdolka** [Lej77/tab-unloader-for-tree-style-tab#4] opened 2018-05-26 08:35 UTC
> Sometimes some tabs fail to restore - they are empty, completely blank, with nothing in the address bar and only with a title on the tab.

tab-unloader-for-tree-style-tab (5.1) has the same bug:
https://github.com/rNeomy/auto-tab-discard/issues/24
The bug has been fixed in this commit
https://github.com/rNeomy/auto-tab-discard/commit/7836ef1cd936fb62ea927d44b91e31638e760bc0
I hope it will help to find a similar solution.

**Steps to reproduce**

* Start Firefox **(60.0.1 (x64))** with clean profile.
* Install TST **2.4.21** - Perhaps this is an optional step. But I'm not sure.
* Install tab-unloader-for-tree-style-tab **5.1** (also I set 500 milliseconds)
* a) Open google.com,
    b) type some search query, like "test"
    c) open ~10 links from search results, wait for full load.
    d) don't visit them (this can be important)
* Unload this tabs via Alt+mouse button, or via context menu (unload tab or unload tree)
* Then visit tabs - some of them were "spoiled".

**Comment by perdolka** [comment] 2018-05-26 08:50
UPD
If you install a both addons at the same time (tab-unloader-for-tree-style-tab and auto-tab-discard)
and use an option "Unload tabs via the auto-tab-discard extension." then the problem does not arise.

**Comment by Lej77** [comment] 2018-05-26 15:40
@perdolka I have released a new version (v5.2) that includes a fix for this issue. Unfortunately the fix requires the `tabs` permission to work and therefore it is disabled by default. To enable it you need to open the options page and request the `tabs` permission from the `Optional Permissions` section. You also need to expand the `Fix for failed tab restore` section and change the number input there from `-1` to something like `500`.

**Comment by Lej77** [comment] 2018-05-29 23:13
@perdolka I made some more improvements to the fix and in version 5.5 it is now enabled with default settings. However, it will only work if it has the "tabs" permission or if Tree Style Tab is installed. Since this extension is made to help with Tree Style Tab this should be most users. 

The fix will probably have slightly better performance with the "tabs" permission since it won't need to get a tab's URL from Tree Style Tab every time a tab is discarded but it shouldn't be noticeable. There are also some edge cases where a tab won't be fixed if the "tabs" permission isn't granted.

**Comment by Lej77** [comment] 2018-06-01 15:46
I have investigated this problem some more and there are still cases where my fix won't work.

## "Broken" tabs

If a tab is discarded with the WebExtension `browser.tabs.discard` function then the tab can be broken so that it won't restore correctly. I haven't observed any "broken" tabs from tabs that are discarded when a window is closed and then re-opened.

I can't find any difference between "broken" tabs and "working" tabs from the information provided by the WebExtensions API, they look the same and seems to have the same `onUpdate` events before they are discarded.

## Behavior of "broken" tabs

If a "broken" tab is activated or reloaded then it will change to the `about:blank` URL and its original URL is lost. (It has the correct URL while it is unloaded.) (This is the issue that my workaround fixes.)

If a "broken" tab is closed then it won't show up in the recently closed tab list and can't be re-opened.

If a window is closed and it contains "broken" tabs then the window will still be added to the recently closed windows. The entry will say that it contains the correct number of tabs but when the window is restored all the "broken" tabs will be created with the `about:blank` URL and their original URL is lost.

If you close Firefox and then use "restore last session" when you start it again (either automatically or manually from the hamburger menu) then none of the "broken" tabs will be opened at all.

**Comment by perdolka** [comment] 2018-06-01 17:07
I added this bug to bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1465558
Can you repeat this information there (if you have an account there) or can I copy it?

**Comment by Lej77** [comment] 2018-06-01 17:20
I don't have an account there yet. You can copy anything you want, I don't mind.

**Comment by perdolka** [comment] 2018-06-01 17:55
OK, thank you.

**Comment by Lej77** [comment] 2018-06-02 02:35
I have released a new version (v5.8) of the extension. It includes a new option that will reload "broken" tab and then unload them again until they are fixed. This will hopefully ensure that no tabs are lost to this bug. It is not enabled by default since it requires the "tabs" permission and some users might be confused why the unloaded tab is reloading. 

The option is a checkbox located in the `Fix for failed tab restore` section. It has quite a long description: 
`When a tab is unloaded with the WebExtensions API it can sometimes be put in a \"broken\" state. A \"broken\" tab can't be re-opened if it is closed (not even with session restore at startup) and when its loaded again it will lose its URL. This option will reload (actually re-setting the tab's URL) \"broken\" tabs and then unload them again. \"Broken\" tabs might need to be reloaded many times before they are fixed. (Compatible with other tab unloaders.)`

**Comment by Lej77** [comment] 2018-09-16 23:32
The Firefox bug that causes this issue seems to be fixed in Firefox 62 (current release version) and I can no longer reproduce the issue. This is not true for Firefox 60 (ESR) where I could still reproduce the issue. So the workaround can still be useful for some users.

**Closed by Lej77** 2018-09-16 23:32 UTC
Labels: Firefox bug, bug

**Comment by chriscjs** [comment] 2019-04-23 04:34
Has anyone noticed if this issue has resurfaced in the last several weeks, at least under Linux.  Strangely in my win10 install it does not happen, but under Arch Linux it does.  I am running Firefox 66, but it also happens in Dev. edition and Nightly.
