### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by perdolka** [Lej77/tab-unloader-for-tree-style-tab#3] opened 2018-05-20 13:22 UTC
Tab Unloader for Tree Style Tab - 4.0
Firefox - 60.0.1 (x64)

"Dim unloaded tabs" doesn't work when i use Alt + one mouse button click.
The clicked tab is suspended but doesn't dimmed.

Temporary solution - double click on tab:
Alt + double mouse button click

Same bug and solution with context menu.

**Comment by Lej77** [comment] 2018-05-20 14:00
This will occur if Tree Style Tab doesn't detect unloaded tabs correctly. The best solution would be to fix Tree Style Tab's code. 

I can't reproduce this issue with a clean profile. I can get this issue when unloading the active tab after installing [Auto Tab Discard](https://addons.mozilla.org/firefox/addon/auto-tab-discard/). If that extension is disabled everything worked as it should again. From my testing this is because that extension causes the tab to change from its discarded state after changing the favicon on the tab to show that it is unloaded. If so then it could fix it in two ways:
 * Unload the tab again after changing the favicon.
 * Add an option for not changing the favicon so that this behavior can be disabled when the user have another way of showing if the tab is unloaded (such as a sidebar).

Do you have that extension installed or is it unrelated to your problem?

**Comment by Lej77** [comment] 2018-05-20 15:43
[This pull request](https://github.com/rNeomy/auto-tab-discard/pull/50) for Auto Tab Discard should fix the issue I observed.

**Comment by Lej77** [comment] 2018-05-25 00:02
My pull request was merged and released in [Auto Tab Discard v0.2.5](https://addons.mozilla.org/firefox/addon/auto-tab-discard/versions/) so the latest version should no longer have that issue. Does this seem to fix your problem as well?

**Comment by Lej77** [comment] 2018-05-25 09:37
@perdolka I suppose I could fix it by just calling the discard function twice. That would have the same effect as your temporary solution. I'll see about implementing that in the next version.

The issue is probably still that Firefox tells extensions that the tab is loaded even though it isn't. This seems to happen if a content script is sending a message when it is being unloaded and my pull request  prevents one such message. It did fix the problem I observed though so I can't reproduce this issue anymore. If this is the reason for this issue then it would be quite hard to fix with in Tree Style Tab's code. If the problem is because of Firefox's tracking then I see two solutions. Either stop the message that is being sent when the tab is unloaded or call the discard function twice (once to unload the tab and another to fix the incorrect Firefox state).

When does tabs get in this incorrect state, is it only when you unload the current tab? Does it happen if you don't use [Auto Tab Discard](https://addons.mozilla.org/firefox/addon/auto-tab-discard/)?

**Comment by perdolka** [comment] 2018-05-25 10:57
Yes, It happen also, when I don't use "Auto Tab Discard" (disabled or uninstalled), 
only "Tab Unloader for Tree Style Tab" (or vice versa).

Only one addon doesn't have this bug - "Tab Unloader (WebExtension)" (Afnan Khan).
But it's NOT integrated into the TST context menu (I think that's the reason why it doesn't have this bug), and has a lot of another cons.

**Comment by Lej77** [comment] 2018-05-25 23:58
@perdolka I have released a new version (v5.0) that includes an option to unload tabs twice. To activate this option you need to open the options page and expand the `Other Settings` section. In it is an option called `When unloading tabs use the unload method again after a slight delay (time in milliseconds) (-1 to disable)`. Set this option to something like `200` and it should hopefully fix your issue.

**Closed** 2018-05-26 16:12 UTC
